### ISSUE TITLE
BrowserAgent Module not found Issue

### ISSUE THREAD

**Issue by hemanthkumaryerra** [newrelic/newrelic-browser-agent#647]
When I am trying to import  browser agent module using **import {BrowserAgent} from 'newrelic/browser-agent/loaders/browser-agent'** but I am getting module not found error. But if I include src path **import {BrowserAgent} from 'newrelic/browser-agent/src/loaders/browser-agent** module would be detected but internal logic of browser agent is throwing some issues.

I followed the steps mentioned in the below url 
https://www-development.newrelic.com/blog/how-to-relic/custom-instrumentation-with-the-new-relic-browser-agent.

**Comment by patrickhousley** [comment]
@hemanthkumaryerra Please provide the below information:

browser agent version:
typescript version:
node version:

Can you also attach copies of any errors you are getting?

**Comment by hemanthkumaryerra** [comment]
Browser Agent Version: 1.237.1
Node Version: 16.16.0
React Js Version: 16.13.1

**Comment by twann503** [comment]
+1 also having same issue.

**Comment by cwli24** [comment]
Hi @hemanthkumaryerra @twann503 , could we get screenshots of the errors on your IDEs please?

**Comment by twann503** [comment]
This is my error after running lint. 

![image](https://github.com/newrelic/newrelic-browser-agent/assets/22675267/1db95367-7370-4b00-b4a2-d1b78d1a3d44)

**Comment by patrickhousley** [comment]
What version of eslint are you running?

**Comment by twann503** [comment]
@patrickhousley v8.43.0

**Comment by patrickhousley** [comment]
Thanks. I will try to take a look at this soon.

**Comment by patrickhousley** [comment]
@twann503 Can I get a copy of your eslint config?

**Comment by twann503** [comment]
@patrickhousley 
`{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "prettier",
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/recommended",
    "plugin:import/electron",
    "plugin:import/typescript"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "rules": {
    "react/react-in-jsx-scope": "off",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }]
  },
  "settings": {
    "react": {
      "version": "detect"
    },
    "import/resolver": {
      "node": {
        "extensions": [".js", ".jsx", ".ts", ".tsx"],
        "moduleDirectory": [".", "node_modules"]
      }
    }
  }
}
`

**Comment by patrickhousley** [comment]
@twann503 Add `typescript: true` to the `settings.'import/resolver'` section and it should resolve the issue.

**Comment by twann503** [comment]
@patrickhousley thank you! that fixed it.

**Comment by patrickhousley** [comment]
Thanks @twann503 for letting me know. @hemanthkumaryerra please let me know if you still need help with this. For now, I am going to close this issue.

**Comment by hieutt2-ssi** [comment]
I have same issue. I'm using eslint: "^7.28.0"

It's my .eslintrc.json

`{
  "env": {
    "browser": true,
    "es2017": true
  },
  "extends": [
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "airbnb",
    "prettier"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2017,
    "sourceType": "module"
  },
  "settings": {
    "import/resolver": {
      "node": {
        "moduleDirectory": ["node_modules", "src/"]
      }
    }
  },
  "plugins": ["react", "@typescript-eslint", "prettier"],
  "rules": {...}
  }
  }`
  
  I tryed adding "typescript: true" but not working for me

**Comment by hemanthkumaryerra** [comment]
I am still facing the same issue.
Attached the screen shot of error I am getting 
![16933028129331397620459552201309](https://github.com/newrelic/newrelic-browser-agent/assets/48920003/d8fe149f-4d61-4874-b6b2-17c06c1097b2)
